# Generated by Django 4.1.1 on 2022-09-15 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название Ивента')),
                ('dt', models.DateField(verbose_name='Дата Ивента')),
                ('tm', models.TimeField(verbose_name='Время Ивента')),
                ('desc', models.CharField(max_length=255, verbose_name='Подробное описание ивента')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.category')),
            ],
        ),
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Привычка')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.category')),
            ],
        ),
        migrations.CreateModel(
            name='HookaCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Категория кальяна')),
            ],
        ),
        migrations.CreateModel(
            name='HookaComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование компонента')),
                ('hook_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.hookacategory')),
            ],
        ),
        migrations.CreateModel(
            name='HookaTobacco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование табака')),
                ('hook_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.hookacomponent')),
            ],
        ),
        migrations.CreateModel(
            name='HookaMixRecept',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название Микса')),
                ('desc', models.CharField(max_length=255, verbose_name='Описание микса')),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.hookatobacco')),
            ],
        ),
        migrations.CreateModel(
            name='Habits_Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.event')),
                ('habit_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.habit')),
            ],
        ),
    ]
