# Generated by Django 4.1.1 on 2022-09-19 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Наименование категории'),
        ),
        migrations.AlterField(
            model_name='event',
            name='desc',
            field=models.CharField(blank=True, max_length=255, verbose_name='Подробное описание ивента'),
        ),
    ]
