# Generated by Django 4.1.1 on 2022-09-19 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_category_name_alter_event_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Запланированно'), ('SUCCES', 'Успешно выполненное'), ('NO_SUCCES', 'Не выполненное'), ('PENDING', 'Отложенное'), ('CANCEL', 'Отмененно')], default=('ACTIVE', 'Запланированно'), max_length=255),
        ),
    ]
