# Generated by Django 4.1.2 on 2022-10-18 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_alter_event_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Наименование категории'),
        ),
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Запланированно'), ('SUCCES', 'Успешно выполненное'), ('NO_SUCCES', 'Не выполненное'), ('PENDING', 'Отложенное'), ('CANCEL', 'Отмененно'), ('In processing', 'Выполняется'), ('passed', 'Прошло')], default='ACTIVE', max_length=255),
        ),
    ]
