# Generated by Django 4.1.2 on 2022-10-19 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_alter_category_name_alter_event_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='dt',
            field=models.DateField(blank=True, verbose_name='Дата Ивента'),
        ),
        migrations.AlterField(
            model_name='event',
            name='tm',
            field=models.TimeField(blank=True, verbose_name='Время Ивента'),
        ),
    ]
