# Generated by Django 4.1.2 on 2022-10-19 15:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_alter_event_dt_alter_event_tm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='dt',
            field=models.DateField(blank=True, default=datetime.date(1999, 1, 1), verbose_name='Дата Ивента'),
        ),
        migrations.AlterField(
            model_name='event',
            name='tm',
            field=models.TimeField(blank=True, default=datetime.time(0, 0), verbose_name='Время Ивента'),
        ),
    ]
