# Generated by Django 4.1.2 on 2022-10-24 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bltochnouser',
            name='age',
            field=models.PositiveIntegerField(blank=True, default=99, verbose_name='Возраст'),
        ),
    ]
