"""empty message

Revision ID: 5fafbf2f7a68
Revises: 8c7910b2a89c
Create Date: 2022-09-03 16:36:39.672779

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5fafbf2f7a68'
down_revision = '8c7910b2a89c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('habits',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('habits_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('habit_id', sa.Integer(), nullable=True),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.ForeignKeyConstraint(['habit_id'], ['habits.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('events', sa.Column('category', sa.Integer(), nullable=True))
    op.add_column('events', sa.Column('dt', sa.Date(), nullable=True))
    op.add_column('events', sa.Column('tm', sa.Time(), nullable=True))
    op.create_foreign_key(None, 'events', 'categories', ['category'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'events', type_='foreignkey')
    op.drop_column('events', 'tm')
    op.drop_column('events', 'dt')
    op.drop_column('events', 'category')
    op.drop_table('habits_events')
    op.drop_table('habits')
    op.drop_table('categories')
    # ### end Alembic commands ###
