"""empty message

Revision ID: b5fe974065c3
Revises: 5fafbf2f7a68
Create Date: 2022-09-03 16:37:10.501469

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b5fe974065c3'
down_revision = '5fafbf2f7a68'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('habits', sa.Column('category', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'habits', 'categories', ['category'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'habits', type_='foreignkey')
    op.drop_column('habits', 'category')
    # ### end Alembic commands ###
